main/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

shop/urls.py
from django.urls import path
from shop import views
from django.views.generic import TemplateView


urlpatterns = [
    # path('fill-database/', views.fill_database, name='fill_database'),
    path('', views.ProductListView.as_view(), name='Магазин'),
    path('cart_view/',  
         views.cart_view, name='Корзина'),
    path('add-item-to-cart/<int:pk>', views.add_item_to_cart, name='add_item_to_cart'),
    path('delete_item/<int:pk>', views.CartDeleteItem.as_view(), name='cart_delete_item'),
    path('make-order/', views.make_order, name='make_order'),
]

shop/models.py
from decimal import Decimal
from django.contrib.auth.models import User
from django.db import models, transaction
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.db.models import Sum


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='product_name')
    code = models.CharField(max_length=255, verbose_name='product_code')
    price = models.DecimalField(max_digits=20, decimal_places=2)
    unit = models.CharField(max_length=255, blank=True, null=True)
    note = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self) -> str:
        return f'{self.name} - {self.price}'

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']
        
    def __str__(self) -> str:
        return f'{self.user} - {self.amount}'
    
    @staticmethod
    def get_balance(user: User):
        amount = Payment.objects.filter(user=user).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)

class Order(models.Model):
    STATUS_CART = '1_cart'
    STATUS_WAITING_FOR_PAYMENT = '2_waiting_for_payment'
    STATUS_PAID = '3_paid'
    STATUS_CHOICES = [
        (STATUS_CART, 'cart'),
        (STATUS_WAITING_FOR_PAYMENT, 'waiting_for_payment'),
        (STATUS_PAID, 'paid')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # items = models.ManyToManyField(OrderItem, related_name='orders')
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=STATUS_CART)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']
        
    def __str__(self) -> str:
        return f'{self.user} - {self.amount} - {self.status}'

    @staticmethod
    def get_cart(user: User):
        cart = Order.objects.filter(user=user,
                                    status=Order.STATUS_CART
                                    ).first()
        if cart and (timezone.now() - cart.creation_time).days > 7:
            cart.delete()
            cart = None
        if not cart:
            cart = Order.objects.create(user=user,
                                    status=Order.STATUS_CART,
                                    amount=0
                                    )
        return cart
    
    def get_amount(self):
        amount = Decimal(0)
        for item in self.orderitem_set.all():
            amount += item.amount
        return amount
    
    def make_order(self):
        items = self.orderitem_set.all()
        if items and self.status == Order.STATUS_CART:
            self.status = Order.STATUS_WAITING_FOR_PAYMENT
            self.save()
            auto_payment_unpayd_orders(self.user)

    @staticmethod
    def  get_amount_of_unpaid_orders(user: User):
        amount = Order.objects.filter(user=user, 
                                      status=Order.STATUS_WAITING_FOR_PAYMENT,
                                     ).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)
     
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=0)  

    class Meta:
        ordering = ['pk']
        
    def __str__(self) -> str:
        return f'{self.product} - {self.price}'
    
    @property
    def amount(self):
        return self.quantity * (self.price - self.discount)


@transaction.atomic()
def auto_payment_unpayd_orders(user: User):
    unpaid_orders = Order.objects.filter(user=user,
                                         status=Order.STATUS_WAITING_FOR_PAYMENT)
    for order in unpaid_orders:
        if Payment.get_balance(user) < order.amount:
            break
        order.payment = Payment.objects.all().last()
        order.status = Order.STATUS_PAID
        order.save()
        Payment.objects.create(user=user,
                               amount=-order.amount)

@receiver(post_save, sender=OrderItem)
def recalculate_order_amount_after_save(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()

@receiver(post_delete, sender=OrderItem)
def recalculate_order_amount_after_delete(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_save, sender=Payment)
def auto_payment(sender, instance, **kwargs):
    user = instance.user
    auto_payment_unpayd_orders(user)

shop/forms.py
from django import forms

from shop.models import OrderItem


class AddQuantityForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['quantity']
        

shop/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from shop.forms import AddQuantityForm
from shop.models import Order, OrderItem, Product
from django.views.generic import ListView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class ProductListView(ListView):
    model = Product
    template_name = 'shop/Магазин.html'


@login_required(login_url=reverse_lazy('login'))
def add_item_to_cart(request, pk):
    if request.method == 'POST':
        quantity_form = AddQuantityForm(request.POST)
        if quantity_form.is_valid():
            quantity = quantity_form.cleaned_data['quantity']
            if quantity:
                cart = Order.get_cart(request.user)
                product = get_object_or_404(Product, pk=pk)
                cart.orderitem_set.create(product=product,
                                          quantity=quantity,
                                          price=product.price)
                cart.save()
                return redirect('Корзина')
        else:
            pass
    return redirect('Магазин')

@login_required(login_url=reverse_lazy('login'))
def cart_view(request):
    cart = Order.get_cart(request.user)
    items = cart.orderitem_set.all()
    context = {
        'cart': cart,
        'items': items,
    }
    return render(request, 'shop/Корзина.html', context)


@method_decorator(login_required, name='dispatch')
class CartDeleteItem(DeleteView):
    model = OrderItem
    template_name = 'shop/Корзина.html'
    success_url = reverse_lazy('Корзина')

    # Проверка доступа
    def get_queryset(self):
        qs = super().get_queryset()
        qs.filter(order__user=self.request.user)
        return qs
    

@login_required(login_url=reverse_lazy('login'))
def make_order(request):
    cart = Order.get_cart(request.user)
    cart.make_order()
    return redirect('Магазин')

templates/shop/Корзина.html
<!DOCTYPE html>
{% extends 'base-page.html' %}
{% load static %}

{% block title %}
    Корзина
{% endblock title %}

{% block container %}
<section class="u-align-center u-clearfix u-section-1" id="sec-4ac9">
    <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
      <div class="u-expanded-width u-table u-table-responsive u-table-1">
        <table class="u-table-entity u-table-entity-1">
          <colgroup>
            <col width="25%">
            <col width="25%">
            <col width="25%">
            <col width="25%">
            <col width="25%">
          </colgroup>
          <tbody class="u-table-alt-palette-1-light-3 u-table-body">
            <tr style="height: 65px;">
              <td class="u-table-cell">Заказ № </td>
              <td class="u-table-cell">Наименование </td>
              <td class="u-table-cell">Кол-во </td>
              <td class="u-table-cell">Сумма </td>
              <td class="u-table-cell">Сумма </td>
            {% for item in items %}
            </tr>
            <tr style="height: 65px;">
              <td class="u-table-cell">{{ forloop.counter }}</td>
              <td class="u-table-cell">{{ item.product }}</td>
              <td class="u-table-cell">{{ item.quantity }}</td>
              <td class="u-table-cell">{{ item.amount }}</td>
              <td class="u-table-cell"><form method="post" action="{% url 'cart_delete_item' item.pk %}">{% csrf_token %}<button type="submit" style="color: blue"><u>delete</u></button></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      
    </div>
  </section>
{% endblock container %}    
   

templates/shop/Магазин.html
<!DOCTYPE html>
{% extends 'base-page.html' %}
{% load static %}

{% block title %}
    Магазин
{% endblock title %}

{% block container %}
<section class="u-align-center u-clearfix u-section-1" id="sec-4ac9">
    <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
      <div class="u-expanded-width u-table u-table-responsive u-table-1">
        <table class="u-table-entity u-table-entity-1">
          <colgroup>
            <col width="25%">
            <col width="25%">
            <col width="25%">
            <col width="25%">
            <col width="25%">
          </colgroup>
          <tbody class="u-table-alt-palette-1-light-3 u-table-body">
            <tr style="height: 65px;">
              <td class="u-table-cell">Заказ № </td>
              <td class="u-table-cell">Наименование </td>
              <td class="u-table-cell">Кол-во </td>
              {% for product in object_list %}
                </tr>
                <form method="post" action="{% url 'add_item_to_cart' product.pk %}">
                <tr style="height: 65px;">
                  <td class="u-table-cell">{{ product.name}}</td>
                  <td class="u-table-cell">{{ product.price }}</td>
                  <td class="u-table-cell"><label class="form-label" for="id_quantity"></label><input type="number" name="quantity" value="1" min="1"required id="id_quantity"/></td>
                  <td class="u-table-cell"><form method="post" action="{% url 'add_item_to_cart' product.pk %}">{% csrf_token %}<button type="submit" style="color: blue"><u>в корзину</u></button></td>                
                </form>
                </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
      
    </div>
  </section>
{% endblock container %}    
   